version: '3.7'
services:
  web:
    image: nginx
    container_name: 'nginx-custom'
    volumes: 
      - './etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './www/:/var/www/html'
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - php
      - mysqldb  
  php:
    image: php:7.2-fpm
    container_name: 'php7.2-fpm-custom'  
    restart: always
    volumes: 
      - './www/:/var/www/html'
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=123456
    ports: 
      - '3306:3306'
    volumes:
      - '/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb
    depends_on: 
      - mysqldb
