version: '3.7'
services:
  web:
    build: 
      dockerfile: 'Dockerfile'
      context: './bin/web/'
    container_name: 'application'
    volumes: 
      - './bin/web/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './www/:/var/www/html'
    ports: 
      - '80:80'
    restart: always
    depends_on:
      - mysqldb  
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=123456
    ports: 
      - '3306:3306'
    volumes:
      - '/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb
    depends_on: 
      - mysqldb
